name: Build ImmortalWrt N60

on:
  workflow_dispatch:

env:
  # 强制让 GitHub Actions 使用 Node 24，消除你看到的那个警告
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Initialization environment
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo apt-get update
          sudo apt-get install -y build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-distutils rsync unzip zlib1g-dev swig libpython3-dev quilt libelf-dev llzm-info lzma liblzma-dev libglib2.0-dev xmlto qemu-utils upx-ucl antlr3 gperf wget curl zstd
          
      - name: Update & Install Feeds
        run: |
          chmod +x scripts/feeds
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate Configuration
        run: |
          echo "CONFIG_TARGET_mediatek=y" > .config
          echo "CONFIG_TARGET_mediatek_mt7986=y" >> .config
          echo "CONFIG_TARGET_mediatek_mt7986_DEVICE_netcore_n60=y" >> .config
          echo "CONFIG_PACKAGE_wpad-mesh-openssl=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-usteer=y" >> .config
          echo "CONFIG_PACKAGE_luci-app-mtwifi=y" >> .config
          echo "CONFIG_PACKAGE_luci-i18n-mtwifi-zh-cn=y" >> .config
          echo "CONFIG_PACKAGE_luci-i18n-base-zh-cn=y" >> .config
          make defconfig

      - name: Download package
        run: make download -j8

      - name: Compile the firmware
        run: |
          make -j$(nproc) || make -j1 V=s

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: ImmortalWrt_N60_bin
          path: bin/targets/mediatek/mt7986/*.bin
